// catch 블록을 비워두면 예외가 무시된다. 아주 의심스러운 코드다!
tyr {
    ...
} catch (SomeException e) {
}
